# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04b5f573eae8f0c13419864a74768993fc8211c69ce9ef054c879c7d2a8221ee3a32d04a3001d4605c45fbeb057abe67b455b03b37f77a98c95e62bcb07656f5

test:
  secret_key_base: c1495eac38053a25a0eb39862fcba6639fd3acd1064285a4ab00a573f602ce07bd1177ee0fb45b12b3ec847cde90f28d8f29479d462afb23d17076a047efafcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
